### PR TITLE
new github action for make magic

### PR DESCRIPTION
**Pull request by hendriktews**

### CODE REVIEW

**Comment by hendriktews** [comment]
failed as expected - I wait now until #545 is merged and continue then to check whether this works as expected

**Comment by hendriktews** [comment]
Fails again as expected. The test here was to change the documentation of a variable that appears in one of the manuals without updating the manual. This time `make -C magic` succeeded, in contrast to the check on Jan 25, where `make` failed.

**Comment by hendriktews** [comment]
Succeeds as expected. This time the manual was changed outside of a magically included variable/function documentation.

**Comment by hendriktews** [comment]
Hi @erikmd, @Matafou, @cpitclaudel, please check whether you are fine with this additional action, that will check in the future if somebody forgot to run `make -C doc magic` after updating the documentation of a variable or function that appears in one of the manuals.

**Comment by Matafou** [comment]
I am all for it. Thanks for this.

**Pull request merged**
