### PR TITLE
Color lia, romega, nia, psatz, nsatz, lra

### LINKED ISSUE #77: `lia`, `romega`, `nia`, `psatz`, `nsatz`, `lra` should all be colored like `omega` and `reflexivity`

### PR DESCRIPTION
**Pull request by JasonGross**
This closes #77

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Great. I'll merge this by cherry-picking.

**Comment by cpitclaudel** [comment]
Thanks, merged!

**Comment by JasonGross** [comment]
Thanks.

By the way, GitHub has this fancy new merge-by-squashing button that doesn't introduce merge commits.

**Comment by cpitclaudel** [comment]
Oooh, shiny. I didn't notice it.
Then again, I generally handle PRs all from Emacs, using the github PR add-on to Magit :) Is there an advantage to using Github's button instead? Authorship is preserved by my method AFAICT, which sounds like the most important point.

**Comment by JasonGross** [comment]
Autoclosing of the issue is the only one I know.  However, if the commits SHAs are preserved (your method seems to not preserve them), then it gets closed automatically anyway.

**Pull request closed without merging**
