### PR TITLE
Implement support for "From ... Require ..."

### LINKED ISSUE #49: Automatic compliation of dependencies does not work with Coq 8.5's "From ... Require Import..."
When a file starts, for example, with
```
From program_logic Require Import ownership.
```
ProofGeneral fails to notice that it has to re-compile the file, and then immediately fails because of inconsistent assumptions about other modules.

### PR DESCRIPTION
**Pull request by RalfJung**
This is my first ever lisp program, so I probably violated every style guideline in existence - I tried to match the surroundings though.

Also, the same still needs to be sine for sequential compilation mode. But this fix means I can go on doing actual work, so that's what I will do next ;-) . If you only want to merge this once sequential mode is also implemented - I can do that, when I feel bored and want to do something different, but not right now.

Fixes #49

### CODE REVIEW

**Comment by RalfJung** [comment]
I just couldn't leave this like that... so I pushed the changes to also compute the module ID properly in sequential mode. ;-)

**Comment by Matafou** [comment]
Thanks a lot Ralf!

Will merge as soon as I have time for it.

P.


2016-02-13 15:56 GMT+01:00 Ralf Jung <notifications@github.com>:

**Comment by hendriktews** [comment]
Thanks for the bug report and the fix. I would like to have a look at the problem and then merge this pull request.

**Comment by RalfJung** [comment]
I updated the PR to fix a problem in sequential mode.

**Comment by hendriktews** [comment]
Thanks for the contribution, the changes somehow made it into master without merging this PR.

**Pull request closed without merging**
