### PR TITLE
Respect user settings in coq-insert-intros

### LINKED ISSUE #67: intros! ignores some of ProofGeneral settings
See https://github.com/cpitclaudel/company-coq/issues/105

### PR DESCRIPTION
**Pull request by cpitclaudel**
Fixes #67.

@Matafou Ok to merge?

### CODE REVIEW

**Comment by Matafou** [comment]
Yes. Done. Thanks!

**Comment by cpitclaudel** [comment]
Hm, did you mean to actually merge this instead of just closing it?

**Comment by Matafou** [comment]
mmh yes I meant merging, thought I did it, sorry.
Should be done now.

**Comment by cpitclaudel** [comment]
Yay :) Thanks for the code review.

**Pull request merged**
