### PR TITLE
enable second stage -vok run for Coq >= 8.11

### PR DESCRIPTION
**Pull request by hendriktews**

### CODE REVIEW

**Comment by hendriktews** [comment]
@RalfJung: are you interested to try this?

**Comment by RalfJung** [comment]
What could/should I try? Would be good to have a brief description of expected behavior. I don't understand the code in this PR.^^

**Comment by hendriktews** [comment]
It adds `coqc -vok`, the feature you asked for in #500. To enable set `coq-compile-vos` to `vos-and-vok`. It's also documented in the manual (in this PR only, of course) and for `coq-compile-vos`.

**Comment by RalfJung** [comment]
I installed this branch and opened some files, and it seems to do something successfully... at least I can see .vok files being created.

Is there anything specific I should be in the look for?

**Comment by hendriktews** [comment]
> Is there anything specific I should be in the look for?

No, nothing specific. Just if it works during normal development.

**Comment by RalfJung** [comment]
Okay. I'll just keep using that branch next week and have my eyes out for any new issues that come up.

Thanks a lot for working on this. :-)

**Comment by hendriktews** [comment]
Rebased to master and updated the last commit that updated the manual. Wrt the feature, nothing has changed.

**Pull request merged**
