### PR TITLE
Omit let fix

### PR DESCRIPTION
**Pull request by hendriktews**

### CODE REVIEW

**Comment by hendriktews** [comment]
This PR adds a commit on top of #694 to fix #687. If #694 changes, I will rebase this PR.

**Comment by hendriktews** [comment]
Similar to #694 , I suggest to merge this PR as is.

**Comment by hendriktews** [comment]
Hi @erikmd and @Matafou , as usual I give you the chance to comment. However, if you are busy or think this is not important enough, it's fine if you ignore the review request. I'll merge then in a week or so.

**Comment by Matafou** [comment]
Sorry I don't have time to review precisely but it seems ok to me. The mechanics for detecting effectfull commands and proofs is a good idea. Once again if we were using the modern protocols for communicating with coq, coq itself would give this information...

**Review by Scutua — APPROVED** [review]

**Pull request merged**
