### PR TITLE
Minor tweaks encountered while trying to run the CI tests

### PR DESCRIPTION
**Pull request by monnier**
* ci/coq-tests.el (070_coq-test-regression-wholefile-no-proof):
Clarify the intention of the test.

* Makefile (check): Fix comment.
(tests): New target.

* .gitignore: Add `ci/.lia.cache`, apparently generated by ci/test.sh

### CODE REVIEW

**Comment by erikmd** [comment]
Hi @monnier! LGTM, thanks! Let us know if you think the PR is ready for merging;

BTW, I've noticed that the CI job for 8.9 took more time than expected and was cancelled… do you believe we need to restart it? anyway I guess that's fine as is.

**Comment by erikmd** [comment]
or the other way around 🙂:

maybe in `.github/workflows/test.yml`, you could commit a change to replace `./ci/test.sh` with `make tests`? WDYT?

**Comment by monnier** [comment]
I don't have much opinion about what `make tests` should do exactly, I added it because that's the place where looked to find the tests (I actually tried `make check` first, then ended up searching through the .github files, since I know nothing about those files but I had a vague inkling that this is where the rules should be found).  I don't know what are the tradeoffs involved in making the github actions use `make tests` either.

**Comment by erikmd** [comment]
OK thanks @monnier!
IMO, I believe that:
- it's better if the `Makefile` targets are representative of the commands we can run (so indeed adding `make tests` makes a lot of sense)
- then just for uniformity, I'd propose we replace the shell command `./ci/test.sh` in the `test.yml` file, with `make tests` (feel free to push another commit for that if you want)
- finally, we may want to add in this PR or later on, a target `make dist-tests` (in a somewhat standard phrasing!) that would run:
  `make tests && make -C ci/compile-tests test && etc…` :)

**Comment by Matafou** [comment]
```ocaml
let x = 12 in
```

**Comment by Matafou** [comment]
sorry wrong clicking

**Comment by erikmd** [comment]
Hi all, Hi @Matafou @hendriktews, just FYI I pushed two commits (including one that I had suggested in a previous comment)
in Stefan's branch (using [git prw](https://github.com/erikmd/git-scripts/#git-prw));

If nobody objects, we'll be able to merge this small PR soon, but **only after PR https://github.com/ProofGeneral/PG/pull/591** I guess:
as we might want to further extend `make dist-tests`with `+$(MAKE) -C ci/test-indent`…

(sorry, I didn't find the time ta take another look at #591 lately :-|)

**Comment by Matafou** [comment]
LGTM.
#591 is ready to merge as far as I can tell.

**Comment by erikmd** [comment]
> LGTM.
> #591 is ready to merge as far as I can tell.

Thanks @Matafou, so I rebased and extend this PR accordingly; will merge it after dinner.

Cheers

**Pull request merged**
