### PR TITLE
Fix typos in custom variable descriptions.

### PR DESCRIPTION
**Pull request by tchajed**

### CODE REVIEW

**Comment by erikmd** [comment]
Thanks @tchajed for the PR!

**Comment by erikmd** [comment]
@Matafou @cpitclaudel 
The target branch of this PR is `master`
I propose to merge this in `master` once 4e0c2a00 and 61941d93 have been cherry-picked in `master`.
Then we'll be able to cherry-pick 0f84e705 (= this PR) in `async`
Any objection?

**Comment by cpitclaudel** [comment]
Sounds good to me.  Or we could merge master in async.

**Comment by erikmd** [comment]
OK thanks @cpitclaudel, I'll do that a bit later.

> Or we could merge master in async.

Indeed that will be even better :+1:

**Comment by erikmd** [comment]
This makes me realize that if some upcoming PRs propose fixes that could be easily applied in both `master` (proof-shell) and `async` branches, we could maybe suggest to preferably set `master` as target branch, then merge in `async`. Even if one such merge adds a little noise in the history, it is more robust actually.
But naturally, if a change only deals with async PG or would be difficult to port in both branches, sticking to `async` as PR target branch is fine ;)

**Comment by cpitclaudel** [comment]
Yup, absolutely

**Comment by erikmd** [comment]
Done.

**Pull request merged**
