### PR TITLE
do not merge: test coq-emacs container action

### PR DESCRIPTION
**Pull request by hendriktews**

### CODE REVIEW

**Comment by hendriktews** [comment]
This PR is solely for testing/developing a new CI action that uses the containers from proofgeneral/coq-emacs. To make testing easier, I deleted all the other actions here - this PR shall not be merged.

**Comment by hendriktews** [comment]
@erikmd : It took me a while to get the permissions and the environment right to run a test with a container from proofgeneral/coq-emacs. Do you have comments or suggestions?

**Comment by erikmd** [comment]
> @erikmd : It took me a while to get the permissions and the environment right to run a test with a container from proofgeneral/coq-emacs. Do you have comments or suggestions?

Hi @hendriktews ! − sorry for late reply.

Yes, using any Docker image with GHA typically raise permissions issues…

FYI I had documented this here:

https://github.com/coq-community/docker-coq-action#permissions

**Comment by hendriktews** [comment]
Containers are used for a long time already in CI.

**Pull request closed without merging**
