### PR TITLE
EasyCrypt PG mode

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks, that's exciting. It's also a bit of a shame that everyone have been too busy to review this in a timely manner.

Before merging this, it would be good to ensure that the code is covered by the right license (it must be GPL), and to add license headers and author and maintainer information to each file. Do you think you can do that?

We are currently in the process of moving PG to ELPA, so we'll need FSF copyright assignment forms from significant contributors to this code, too. Is it known who wrote it? Did you?

Thanks!

**Comment by strub** [comment]
No problem to move it under GPL, with an IMDEA/Inria copyright. Currently,
I'm the main author of that mode (we used to have a former version of this
mode, but it has been entirely rewritten), with some inspiration from the
Coq mode.

2016-02-03 4:19 GMT+01:00 Clément Pit--Claudel <notifications@github.com>:

**Comment by cpitclaudel** [comment]
Thanks. The IMDEA license will do, but we will need a copyright transfer to FSF if we want to keep easycrypt support in when we move to ELPA. See [my email to pg-devel](http://lists.inf.ed.ac.uk/pipermail/proofgeneral-devel/2016/000372.html) for more info on this.

Emacs Lisp source code has a fixed format for headers; running `checkdoc` on the various .el files will guide you through adding the appropriate ones. Or you could draw inspiration from files already in PG, such as https://github.com/ProofGeneral/PG/blob/master/coq/coq-par-compile.el (though plenty of files already in pG don't adhere to the conventions... :/)

**Comment by strub** [comment]
Could you point me to the form that has to be fill by our institutes (Inria & IMDEA) and to whom it has to be communicated?

**Comment by cpitclaudel** [comment]
Definitely!

```
Please email the following information to assign@gnu.org, and we
will send you the assignment form for your past and future changes.

Please use your full legal name (in ASCII characters) as the subject
line of the message.
----------------------------------------------------------------------
REQUEST: SEND FORM FOR PAST AND FUTURE CHANGES

[What is the name of the program or package you're contributing to?]
GNU Emacs

[Did you copy any files or text written by someone else in these changes?
Even if that material is free software, we need to know about it.]


[Do you have an employer who might have a basis to claim to own
your changes?  Do you attend a school which might make such a claim?]


[For the copyright registration, what country are you a citizen of?]


[What year were you born?]


[Please write your email address here.]


[Please write your postal address here.]


[Which files have you changed so far, and which new files have you written
so far?]

```

**Comment by hendriktews** [comment]
@cpitclaudel the license information is there, we can merge I think?

@strub Could you add a small example with the necessary instruction about how to try it out?

**Comment by cpitclaudel** [comment]
Sure.

**Comment by hendriktews** [comment]
@strub thanks for your contribution and please accept our apologies for the long delay.

**Pull request merged**
