### PR TITLE
basic proof tree changes for Coq 8.5

### PR DESCRIPTION
**Pull request by hendriktews**
Fixes to get basic proof tree functionality, including support for
give_up, cycle, swap, revgoals. Unshelve and evar's don't work yet, see
proof-tree issues #1 and #2

### CODE REVIEW

**Comment by Matafou** [comment]
Great! Thanks Hendrik. Will test/merge.
P
Le dim. 24 janv. 2016 à 16:22, hendriktews <notifications@github.com> a
écrit :

**Comment by cpitclaudel** [comment]
Hendrik, I just realise that you didn't have commit rights. Sorry about that. It should be fixed now. I can only add you to the PG repository; @DavidAspinall will either need to make me a co-owner of the organization, or add you to the admin team himself.

**Comment by Matafou** [comment]
Should we merge this?
P.

**Comment by Matafou** [comment]
Merged. Thanks Hendrik.

**Pull request merged**
