### PR TITLE
Remove mmm and ML4PG contribs 

### PR DESCRIPTION
**Pull request by psteckler**
Per issue #171, removing mmm-mode. Also, we've learned that ML4PG is no longer maintained. These were the only two items in the contrib/ directory.

I've attempted to remove all references to mmm and ML4PG in the code and docs.

### CODE REVIEW

**Comment by Matafou** [comment]
LGTM

**Comment by Matafou** [comment]
AFter taking a closer look there are still some problematic reference to mmm mode in files.

~/pg/psteckler$ rgrep mmm *
generic/proof-autoloads.el:;;;### (autoloads (proof-mmm-enable proof-mmm-set-global) "proof-mmm"
generic/proof-autoloads.el:;;;;;;  "proof-mmm.el" (20118 50210))
generic/proof-autoloads.el:;;; Generated autoloads from proof-mmm.el
generic/proof-autoloads.el:(autoload 'proof-mmm-set-global "proof-mmm" "\
generic/proof-autoloads.el:(autoload 'proof-mmm-enable "proof-mmm" "\
generic/proof-autoloads.el:This invokes `mmm-mode' to toggle the setting for the current
generic/proof-auxmodes.el:(defun proof-mmm-support-available ()
generic/proof-auxmodes.el:  "A test to see whether mmm support is available."
generic/proof-auxmodes.el:   (or (featurep 'mmm-auto)
generic/proof-auxmodes.el:		(concat proof-home-directory "contrib/mmm/"))
generic/proof-auxmodes.el:	 (proof-try-require 'mmm-auto)))
generic/proof-auxmodes.el:   ;; Load prover-specific config in <foo>-mmm.el
generic/proof-auxmodes.el:   (proof-try-require (proof-ass-sym mmm))))
generic/proof-auxmodes.el:    (if (and (proof-ass mmm-enable)
generic/proof-auxmodes.el:	     (proof-mmm-support-available))
generic/proof-auxmodes.el:	(proof-mmm-set-global t)))
generic/proof-menu.el:  (proof-deftoggle-fn (proof-ass-sym mmm-enable) 'proof-mmm-toggle))
generic/proof-menu.el:     ["Multiple Modes" (proof-mmm-toggle (if mmm-mode 0 1))
generic/proof-menu.el:      :active (proof-mmm-support-available)
generic/proof-menu.el:      :selected (and (boundp 'mmm-mode) mmm-mode)
generic/proof-menu.el:   (proof-ass-sym mmm-enable)
generic/pg-custom.el:(defpgcustom mmm-enable nil
Binary file hol-light/TacticRecording/ex3.png matches
Binary file images/ProofGeneral.png matches
Binary file images/epg-context.png matches
lib/holes.el:  (unless (boundp 'mmm-inside-insert-by-key) ; pc: this hack is ok for me
lib/pg-dev.el:     proof-easy-config proof-config proof-mmm proof
lib/pg-dev.el:     isar-autotest interface-setup isabelle-system isar isar-mmm
Makefile:OTHER_ELISP=generic lib contrib/mmm
pg-init.el:         '("contrib/mmm" "generic" "lib"

**Comment by psteckler** [comment]
@Matafou Thanks, most of those were files I'd edited, but not committed in my PR branch.

The `.png` files contain the letters "mmm", but that's just a coincidence.

**Comment by psteckler** [comment]
I'm going to squash the commits, to make it easier to merge back the changes to PG/xml.

**Comment by psteckler** [comment]
@Matafou OK if I merge this, then?

**Comment by Matafou** [comment]
Yes.
P

**Comment by cpitclaudel** [comment]
Good for me too :) Sorry for the delay.

**Comment by cpitclaudel** [comment]
Thanks @Matafou and @psteckler!

**Comment by erikmd** [comment]
Likewise for me, thanks @psteckler for this PR!

**Pull request merged**
