### PR TITLE
coq-par-compile: use hash for ancestors

### LINKED ISSUE #499: emacs eats up all my RAM while processing imports
I am having trouble using PG on a particular Coq development, where when I step over the `Require` commands at the top of the file it never completes, instead eating up all of my RAM until the machine starts thrashing. When I killed it the emacs process was at more than 80% of my 16GB RAM. Running `make` in the same project to build it all with `coqc` works fine.

To reproduce, clone https://github.com/mit-pdos/perennial, initialize submodules (`git submodule update --init --recursive`), and then open pretty much any file and step to the end of the buffer in PG. I tried `external/Goose/github_com/mit_pdos/perennial_examples/replicated_block.v` and `src/program_logic/crash_weakestpre.v`.

This is with latest PG master and emacs 1:26.3+1-2 on Debian testing.

### PR DESCRIPTION
**Pull request by hendriktews**
The hash avoids an exponentially growing number of duplicates in
the ancestor collection. Fixes #499

### CODE REVIEW

**Comment by hendriktews** [comment]
Where can I find something about the test that is failing here?

**Comment by erikmd** [comment]
Hi @hendriktews, you can just click on the [Checks tab](https://github.com/ProofGeneral/PG/pull/503/checks) of the PR.
But actually it seems [the error](https://github.com/ProofGeneral/PG/runs/789430829#step:5:1240) is a spurious failure (the test `020_coq-test-definition` fails with Coq 8.10 because at the time the assertion is checked, the expected text in **\*response\*** buffer is not there), so I guess we can just ignore that error!
(and I'll try to have a look on this later on to make the test more robust)

**Comment by hendriktews** [comment]
> Hi @hendriktews, you can just click on the [Checks tab](https://github.com/ProofGeneral/PG/pull/503/checks) of the PR.

Yes, but there I only see that test (8.10, minimal) fails. Where can I find a description of the test that fails or its source code? Finding out that it is 020_coq-test-definition is already difficult, because this is somewhere hidden in the middle of the log.

I really appreciate that we have continuous integration now and even with automated tests! I am willing to investigate, when something fails on one of my RP's, but I don't really know how.

**Comment by hendriktews** [comment]
> do you need that @RalfJung performs another test before the merge?

It would of course be nice, but I don't think it is required. I tested it on @RalfJung's repo and also tested it with an compilation error and `coq-compile-keep-going`...

**Comment by erikmd** [comment]
@hendriktews 

>Yes, but there I only see that test (8.10, minimal) fails. Where can I find a description of the test that fails or its source code? Finding out that it is 020_coq-test-definition is already difficult, because this is somewhere hidden in the middle of the log.
> I really appreciate that we have continuous integration now and even with automated tests! I am willing to investigate, when something fails on one of my RP's, but I don't really know how.

Yes, the interface of GitHub Actions logs is not extremely intuitive, but to summarize:
* First click on the Checks tab − https://github.com/ProofGeneral/PG/pull/503/checks
* Click on the workflow name, **CI** (on the top-left of the Checks page, cf. screenshot below)
    2020-06-22_22-48-29_Screenshot_PG_CI
* You are now at page https://github.com/ProofGeneral/PG/actions/runs/141279705
* You can see the name of the tests that failed (cf. screenshot below)
2020-06-22_22-50-14_Screenshot_Problem_matcher
* (If only one version of Coq is concerned, this might be a spurious failure)
* If need be, you can grep the test name in that file to get the code: https://github.com/ProofGeneral/PG/blob/master/ci/coq-tests.el  
    https://github.com/ProofGeneral/PG/blob/5cc231625e2b4a2e4b4d4caf088a44e9c4f1259e/ci/coq-tests.el#L192-L200
* For further details, you can either:
  * Re-run the test locally in batch mode by doing `cd .../PG/ci && ./test.sh`
  * Re-run the test locally in interactive mode with − cf. https://github.com/ProofGeneral/PG/pull/495#issuecomment-635437724 :  
        <kbd>C-x C-f ci/coq-tests.el RET</kbd><kbd>M-: (progn (load-file "coq-tests.el") (call-interactively #'ert)) RET</kbd>
  * Or directly browse the GitHub Actions log, by clicking successively on:
        2020-06-22_22-56-40_Screenshot_Fail_1  
        ↓
        2020-06-22_22-56-56_Screenshot_Fail_2  
        ↓
        2020-06-22_22-57-31_Screenshot_Fail_3  
        ↓
        2020-06-22_22-57-56_Screenshot_Fail_4  
        (the main error line is automatically recognized (by a [custom regexp](https://github.com/ProofGeneral/PG/blob/5cc231625e2b4a2e4b4d4caf088a44e9c4f1259e/.github/ert.json#L8)) and underlined in red − this is the so-called Problem Matcher feature of GitHub Action)

**Pull request merged**
