### PR TITLE
Remove default absolute name from coq-prog-name (Fixes #76), but keep displaying…

### LINKED ISSUE #76: Why do we call proof-locate-executable on coq-prog-name (et al)?
This is the definition of `coq-prog-name`:

```
(defcustom coq-prog-name
  (proof-locate-executable "coqtop" t '("C:/Program Files/Coq/bin"))
```

Why do we need the proof-locate-executable part?

IIUC this computes an absolute path. The problem is that this prevents us from running PG in Tramp. 

Currently, running Coq remotely in Tramp only works when Coq isn't installed on the local machine, because coq-prog-name ends up being set to just `coqtop` in that case. But if Coq is installed, then we pass the full path of the local Coq binary to the remote server via tramp, and of course that doesn't work (the Coq binary isn't in the same location on the remote machine).

Just setting `coq-prog-name` to "coqtop" seems to work fine, though. Maybe we could do that?

### PR DESCRIPTION
**Pull request by Matafou**
… it when asking for it.

Fixing #76 trying to satisfy everyone: tramp users, windows users and users switching coq versions often.

Basically use "coqtop" everywhere except if coqtop is found outside windows path.
Show the absolute filename when asking the proof-prog-name interactivelt.

### CODE REVIEW

**Comment by hendriktews** [comment]
I would suggest to change the calls for coq-dependency-analyzer and coq-compiler in the same way as for coq-prog-name.

**Comment by hendriktews** [comment]
... and I would suggest to include ``(fixes #76)'' in the commit message to save one click when this PR gets merged

**Comment by Matafou** [comment]
Done.

**Comment by Matafou** [comment]
I will merge this if no more comment.

**Comment by patcaslm** [comment]
This commit seems to be causing problems on MacOs. Since I did a git pull a few days ago, Proof General cannot find the coq binaries anymore.

**Comment by cpitclaudel** [comment]
@patcaslm Can you give more details about your config? Where are your coq binaries, which errors do you get, etc?

**Comment by patcaslm** [comment]
I did more digging and now I am not so sure the problem is because of the changes to coq-system.el. I evaluated the buffer with coq-system.el and then looked at the variables coq-prog-name, coc-dependency-analyzer, and coq-compiler and their values were "coqtop", "coqdep", and, respectively, "coqc", which seems just right. These binaries are in the PATH variable and I can invoke them from the terminal. The problem is that Proof General, for some reason, cannot find them. I could see errors like the following in the logs:

/bin/bash: coqtop: command not found
proof-activate-scripting: Searching for program: No such file or directory, coqtop

This doesn't make sense to me. I can execute coqtop with bash, in the terminal. Any ideas?

**Comment by cpitclaudel** [comment]
How are you starting emacs? It could be that Emacs doesn't inherit your path properly.

**Comment by Matafou** [comment]
Hi,
It looks like you don"t have the right PATH in your X session. 

Try M-! echo $PATH

to see what is the path of the shell you call from emacs (path inherited from the X session).

Fixing this needs to understand how your X session manager (gdm, xdm etc) reads you shell config files.

**Comment by Matafou** [comment]
mmh I read too fast. If the variable a set correctly then it is not X session problem.

**Comment by cpitclaudel** [comment]
My personal bet would be that Emacs is being started from the dock, not from the command line

**Comment by Matafou** [comment]
Probably yes. But if the coq-prog-name is set correctly it means that the path is visible somewhere but not everywhere.

@patcaslm Can you please compare the result of

M-! echo $PATH
and the value of variable exec-path?

Are you using aquamacs?

**Comment by patcaslm** [comment]
Hi everyone,

I rebooted and everything works well now.

The problem was indeed with the PATH that emacs was seeing (both Aquamacs and Emacs, and it didn't matter if they were started from the Dock or from a terminal -- weird). A few days ago I installed Coq 8.6 from Opam (until then I used to use Macports). At the same time I also updated Proof General. But the problem seems to have been caused by the new installation of Coq.

Thanks for your help. You put me on the right track 👍

**Pull request merged**
