### PR TITLE
docs: Update README.md

### PR DESCRIPTION
**Pull request by erikmd**
Small (2-commit) PR:

* Remove obsolete info
* Add links (https://coq.zulipchat.com, https://coq.gitlab.io/zulip-archive)

### CODE REVIEW

**Review by Matafou — APPROVED** [review]
LGTM

**Comment by erikmd** [comment]
Thanks @Matafou, feel free to merge (either with `Squash-Merge` or with a true `Merge` then, as you want)

**Review by monnier — APPROVED** [review]
Thanks for catching this other GPLv2 left over

**Comment by hendriktews** [comment]
restarted checks because the prelude check failed for 8.9/26.1

**Comment by hendriktews** [comment]
now the indentation test 26.1 fails - trying again

**Comment by hendriktews** [comment]
test-indent 26.1 seems to fail reliably - no idea why it is canceled

**Comment by Matafou** [comment]
Strange indeed. @erikmd do you have an idea?

**Comment by erikmd** [comment]
> Strange indeed. @erikmd do you have an idea?

maybe it was just a transient bug…

the whole CI is green now, so, let's merge this one.

**Pull request merged**
